# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-28 15:27
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='profile/')),
                ('contacts', models.CharField(blank=True, max_length=50)),
                ('Project', models.CharField(blank=True, max_length=50)),
                ('bio', models.CharField(blank=True, max_length=100)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('view', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('link', models.CharField(blank=True, max_length=50)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)])),
                ('usability', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)])),
                ('content', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)])),
                ('project', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
