# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-28 09:36
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Wards', '0002_project_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)])),
                ('usability', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)])),
                ('content', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)])),
                ('project', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='website',
            new_name='Project',
        ),
    ]
